name: coarse_widgets
description: A Package with predefined components to ease the development cycle.
version: 0.0.3
homepage: https://github.com/GhagSagar23/coarse_widgets

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  flutter_spinkit: ^5.1.0
  package_info_plus: ^1.4.0
  pin_code_fields: ^7.3.0

  # Console Logging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4